version: "3.7"
services:
  absence-mailer:
    build: .
    container_name: absence-mailer
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      ABSENCE_ID: ${ABSENCE_ID}
      ABSENCE_KEY: ${ABSENCE_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_AUTH_USER: ${SMTP_AUTH_USER}
      SMTP_AUTH_PASS: ${SMTP_AUTH_PASS}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_TO: ${MAIL_TO}
      CRON_EXPRESSION: ${CRON_EXPRESSION}
      CRON_TIME_ZONE: ${CRON_TIME_ZONE}
